### ISSUE TITLE
Скроллинг

### ISSUE THREAD

**Issue by cliffis** [shubnikofff/teleport#12]
Нужно сделать скроллинг для списка компаний на страничке создания заявки. Так, чтобы вся заявка убиралась на экране без прокрутки.

**Comment by shubnikofff** [comment]
Нужно выделить фиксированную по высоте область для списка компаний. Высота формы заявки на разных моторах будет разная.

**Comment by shubnikofff** [comment]
В фиксированной области будет осуществляться скролинг

**Comment by shubnikofff** [comment]
Done
