### ISSUE TITLE
Иконизация

### ISSUE THREAD

**Issue by cliffis** [shubnikofff/teleport#13]
1. На общем графике нужно поменять значек записи на красную большую точку( размер покажу). И поместить её в правый нижний угол.
2. Слова codian,  polycom, нужно заменить соответствующими иконками. Размер такой же, как у "точки" записи. Расположить так же в правом нижнем углу, только перед значком записи. 
3. Нужно придумать значок или ещё что либо, для отличия вкс от простого совещания.

**Comment by shubnikofff** [comment]
Тоже думал о том чтобы запись, режим совещания и сервер сборки отображать в виде иконок - выигрываем место для остальной информации

**Comment by shubnikofff** [comment]
1. Значок записи оставил прежним, так как он более информативен и понятен. Если нужно - могу переделать.
2. Предлагаю проблему отображения серверов сборки вынести в отдельный тикет, когда будет ясность с бизнес логикой
3. Done

Все иконки расположены в правом **верхнем** углу, так как там 100% вероятность того что они не будут "съедены" при рендеринге страницы
