### ISSUE TITLE
Красная полоска

### ISSUE THREAD

**Issue by cliffis** [shubnikofff/teleport#14]
Во второй половине дня красная полоска пропала. Появилась ближе к вечеру, но не на графике, а над графиком.

**Comment by shubnikofff** [comment]
Fixed. Теперь полоса текущего времени появляется только если выбрана текущая дата.

**Comment by shubnikofff** [comment]
Current time line should print between min and max time values.

**Comment by shubnikofff** [comment]
Fixed
