### ISSUE TITLE
Телефонный справочник

### ISSUE THREAD

**Issue by cliffis** [shubnikofff/teleport#18]
Убрать из телефонного справочника, формы заявок:
1. Заявка на видеоконференцсвязь
2. Список переговорных комнат, оборудованных видеоконференцсвязью (ВКС)
3. Найти аудиозаписи прошедших ВКС можно здесь.
    Гарантированный срок хранения записи - 1 месяц с момента проведения ВКС.

**Comment by shubnikofff** [comment]
Done
