### ISSUE TITLE
Запись

### ISSUE THREAD

**Issue by cliffis** [shubnikofff/teleport#5]
1.Создать ссылку на архив записей ВКС. Доступно только для зарегистрированных пользователей.
Размещение нужно обсудить.
2. При создании новой заявки пользователем, справа от слова "Аудиозапись" должен появляться текст "срок хранения 1 мес." (на один пункт меньше шрифтом и буквы красным цветом). При условии, если галка установлена.

**Comment by shubnikofff** [comment]
Надпись "Архив аудиозаписей" можно поместить рядом с "Подать заявку"

**Comment by shubnikofff** [comment]
1. Done.
2. Done. Оформление сделал в общей стилистике в виде help block. Если не понравиться, откроем проблему заново.
