### ISSUE TITLE
Яркая запись

### ISSUE THREAD

**Issue by cliffis** [shubnikofff/teleport#8]
В заявке, если помечено, что требуется запись, то слово "да" выделить красным, а может и жирным.

**Comment by shubnikofff** [comment]
Она сейчас и так жирная . Буду думать по поводу цвета

**Comment by cliffis** [comment]
надо, чтобы она бросалась в глаза, когда сотрудник ОСКР открывает заявку.

**Comment by shubnikofff** [comment]
Done
